a=int(input("Enter the number a"))
b=int(input("Enter the number b"))
print(f"The numbers are {a} & {b}")
print(f"Sum {a+b}")
print(f"Difference {a-b}")
print(f"Product {a*b}")
print(f"Integer Quotient {int(a/b)}")
print(f"Fractional Quotient {a/b}")
print(f"Remainder {a%b}")